USE NORTHWIND;
SELECT * FROM CUSTOMERS;
SELECT CUSTOMERNAME, CITY, COUNTRY FROM CUSTOMERS;
SELECT PRODUCTID, PRODUCTNAME FROM PRODUCTS;
SELECT COUNTRY FROM CUSTOMERS;
SELECT distinct COUNTRY FROM CUSTOMERS;
SELECT count(distinct COUNTRY) FROM CUSTOMERS;
SELECT distinct CITY FROM SUPPLIERS;
SELECT COUNT(DISTINCT CITY) FROM CUSTOMERS;
SELECT * FROM customers WHERE COUNTRY = "MEXICO";
SELECT * FROM PRODUCTS WHERE PRODUCTID = 1;
SELECT * FROM CUSTOMERS WHERE CITY = "LONDON";
SELECT count(*) FROM CUSTOMERS WHERE COUNTRY = "USA";
SELECT * FROM PRODUCTS WHERE PRICE > 100;
SELECT * FROM CUSTOMERS WHERE CUSTOMERID >= 15;
SELECT * FROM EMPLOYEES WHERE BIRTHDATE > "1960-01-01";
SELECT * FROM CUSTOMERS WHERE COUNTRY = "GERMANY" AND CITY = "BERLIN";
SELECT * FROM SUPPLIERS WHERE COUNTRY = "JAPAN" AND CITY = "TOKYO";
SELECT * FROM CUSTOMERS WHERE COUNTRY = "UK" AND CITY = "LONDON";
SELECT * FROM PRODUCTS WHERE PRICE < 5 AND PRODUCTID > 10;
SELECT * FROM CUSTOMERS WHERE COUNTRY = "UK" OR COUNTRY = "USA";
SELECT * FROM CUSTOMERS WHERE COUNTRY = "PORTLAND" OR COUNTRY = "KIRKLAND";
SELECT * FROM ORDERS WHERE ORDERDATE < "1996-08-27" OR ORDERDATE > "1997-02-21"; 
SELECT * FROM CUSTOMERS ORDER BY COUNTRY;
SELECT * FROM PRODUCTS ORDER BY PRICE;
SELECT ProductName, Price FROM Products ORDER BY Price DESC;
SELECT * FROM Customers ORDER BY Country, CustomerName;
SELECT * FROM Customers ORDER BY CustomerName, COUNTRY;
SELECT * FROM EMPLOYEES ORDER BY LASTNAME , BIRTHDATE, "DESC";
SELECT * FROM Customers where country = 'usa' order by customername;
SELECT * FROM Customers LIMIT 5;
SELECT * FROM Products ORDER BY PRICE LIMIT 5;
SELECT * FROM Customers WHERE Country='Germany' LIMIT 3;
SELECT * FROM Products WHERE CategoryID=1 LIMIT 3;
SELECT * FROM Products WHERE Price > 20 ORDER BY Price DESC LIMIT 10;
SELECT * FROM Customers WHERE City = 'London' ORDER BY CustomerID LIMIT 3;
SELECT MIN(Price) AS SmallestPrice FROM Products;
SELECT MAX(Price) AS LargestPrice FROM Products;
SELECT AVG(Price) FROM Products;
SELECT SUM(Quantity) FROM OrderDetails;













