USE NORTHWIND;
SELECT * FROM CUSTOMERS;
SELECT CUSTOMERNAME, CITY, COUNTRY FROM CUSTOMERS;
SELECT PRODUCTID, PRODUCTNAME FROM PRODUCTS;
SELECT COUNTRY FROM CUSTOMERS;
SELECT distinct COUNTRY FROM CUSTOMERS;
SELECT count(distinct COUNTRY) FROM CUSTOMERS;
SELECT distinct CITY FROM SUPPLIERS;
SELECT COUNT(DISTINCT CITY) FROM CUSTOMERS;
SELECT * FROM customers WHERE COUNTRY = "MEXICO";
SELECT * FROM PRODUCTS WHERE PRODUCTID = 1;
SELECT * FROM CUSTOMERS WHERE CITY = "LONDON";
SELECT count(*) FROM CUSTOMERS WHERE COUNTRY = "USA";
SELECT * FROM PRODUCTS WHERE PRICE > 100;
SELECT * FROM CUSTOMERS WHERE CUSTOMERID >= 15;
SELECT * FROM EMPLOYEES WHERE BIRTHDATE > "1960-01-01";
SELECT * FROM CUSTOMERS WHERE COUNTRY = "GERMANY" AND CITY = "BERLIN";
SELECT * FROM SUPPLIERS WHERE COUNTRY = "JAPAN" AND CITY = "TOKYO";
SELECT * FROM CUSTOMERS WHERE COUNTRY = "UK" AND CITY = "LONDON";
SELECT * FROM PRODUCTS WHERE PRICE < 5 AND PRODUCTID > 10;
SELECT * FROM CUSTOMERS WHERE COUNTRY = "UK" OR COUNTRY = "USA";
SELECT * FROM CUSTOMERS WHERE COUNTRY = "PORTLAND" OR COUNTRY = "KIRKLAND";
SELECT * FROM ORDERS WHERE ORDERDATE < "1996-08-27" OR ORDERDATE > "1997-02-21"; 
SELECT * FROM CUSTOMERS ORDER BY COUNTRY;
SELECT * FROM PRODUCTS ORDER BY PRICE;
SELECT ProductName, Price FROM Products ORDER BY Price DESC;
SELECT * FROM Customers ORDER BY Country, CustomerName;
SELECT * FROM Customers ORDER BY CustomerName, COUNTRY;
SELECT * FROM EMPLOYEES ORDER BY LASTNAME , BIRTHDATE, "DESC";
SELECT * FROM Customers where country = 'usa' order by customername;
SELECT * FROM Customers LIMIT 5;
SELECT * FROM Products ORDER BY PRICE LIMIT 5;
SELECT * FROM Customers WHERE CustomerName LIKE 'a%';
SELECT * FROM Customers WHERE CustomerName LIKE '%a';
SELECT * FROM Customers WHERE CustomerName LIKE '%GODOS%';
SELECT * FROM Customers WHERE CustomerName LIKE '_r%';
SELECT * FROM Customers WHERE CustomerName LIKE '_O%';
SELECT * FROM Customers WHERE CustomerName LIKE 'a__%';
SELECT * FROM Customers WHERE ContactName LIKE 'a%o';
SELECT * FROM Customers WHERE CustomerName LIKE 'a__%' AND CUSTOMERNAME LIKE "G%";
SELECT * FROM Customers WHERE CustomerName LIKE 'a__%' OR CUSTOMERNAME LIKE "G%";
SELECT * FROM Customers WHERE NOT CUSTOMERNAME LIKE "G%";
SELECT SupplierName, Country FROM suppliers WHERE Country LIKE '%land%';
SELECT FirstName, EmployeeID FROM employees WHERE FirstName LIKE '_n%';
SELECT ShipperName, ShipperID FROM shippers WHERE ShipperName LIKE '%Express%';
SELECT * FROM Customers WHERE Country IN ('Germany', 'France', 'UK');
SELECT * FROM Customers WHERE Country NOT IN ('Germany', 'France', 'UK');
SELECT * FROM Customers WHERE Country = 'Germany' OR Country = 'France' OR Country = 'UK';
SELECT * FROM Customers WHERE Country IN (SELECT Country FROM Suppliers);
select * from products where productname in (select categoryname from categories);
SELECT * FROM Customers WHERE City IN ('Berlin', 'Paris', 'Madrid');
SELECT * FROM Customers WHERE CustomerID IN (SELECT CustomerID FROM Orders);
SELECT * FROM Orders WHERE ShipperID IN (1, 3);
SELECT * FROM Products WHERE Price IN (10, 20, 30);
SELECT * FROM Products WHERE Price BETWEEN 10 AND 20;
































